spring:
  application:
    name: sensorai
  ai.ollama:
    base-url: http://localhost:11434
    chat.options:
      model: llama3.2
      temperature: 0.4

server:
  port: 8083
#  servlet:
#    context-path: /sensorai

sensor-manager.url: http://localhost:8090/temperaturesensor/graphql


