spring:
  application:
    name: sensorai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat.options:
        model: llama3.2
        temperature: 0.4
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
    chat:
      client:
        enabled: false
    active-model: ollama
#    active-model: anthropic

server:
  port: 8083
#  servlet:
#    context-path: /sensorai

sensor-manager.url: http://localhost:8090/temperaturesensor/graphql

eureka:
  client:
    #        enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

mcp.sensor-mcp-server.base-url: http://localhost:8084
