spring.application.name: sensoreureka

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
#    prefer-ip-address: true
    hostname: localhost

#spring:
#  cloud:
#    inetutils:
#      ignored-interfaces: vEthernet*
#      preferred-networks:
#        - 192.168
#      defaultIpAddress: 192.168.50.128

#management:
#  zipkin:
#    tracing:
#      endpoint: http://192.168.50.158:9411/api/v2/spans
